### ISSUE TITLE
kotlin version

### ISSUE THREAD

**Issue by zhangqifan1** [skydoves/Rainbow#2]
![图片](https://user-images.githubusercontent.com/29973474/118227184-b3e55500-b4ba-11eb-95c9-8b3b0d7ecca1.png)
![图片](https://user-images.githubusercontent.com/29973474/118227220-c069ad80-b4ba-11eb-8b88-765827696fd3.png)
Excuse me,how to solve it ?

**Comment by skydoves** [comment]
Hi, please add the below codes to your `gradle.build` module like [here](https://github.com/skydoves/Rainbow/blob/master/rainbow/build.gradle#L27).

```kotlin
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += [
            "-Xuse-experimental=kotlin.Experimental",
        ]
        languageVersion = "1.5"
        apiVersion = "1.5"
    }
}
```

**Comment by zhangqifan1** [comment]
i have tried it,but it still have error like that......

**Comment by loopforge** [comment]
Same issue with me, I tried the above code but it didn't fix the issue. Please add kotlin support

**Comment by skydoves** [comment]
Hi, I just found the solution.

1. Add the blow codes in your gradle file.
```gradle
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += [
            "-Xuse-experimental=kotlin.Experimental",
            "-Xskip-prerelease-check",
        ]
        languageVersion = "1.5"
        apiVersion = "1.5"
    }
}
```

2. Go to your Settings -> Kotlin Compiler -> and add the below option on your `Additional command line parameters`:
```
-Xuse-experimental=kotlin.Experimental
```
![screenshot1974719785](https://user-images.githubusercontent.com/24237865/118307846-36572e80-b526-11eb-9c70-9f31c1e05ecf.png)

**Comment by zhangqifan1** [comment]
thanks .it ' s ok
